-- Migration: Create a trigger for the notify_contact_addition edge function
-- Executed at: 2025-07-17T20:05:04Z
-- Generated by AI Agent

CREATE OR REPLACE FUNCTION notify_contact_addition_trigger()
RETURNS TRIGGER AS $$
BEGIN
  PERFORM net.http_post(
    'https://your-supabase-instance.functions.supabase.co/notify_contact_addition',
    json_build_object('record', NEW)
  );
  RETURN NEW;
END;
$$ LANGUAGE plpgsql;

CREATE TRIGGER on_contact_insert
AFTER INSERT ON contacts
FOR EACH ROW EXECUTE FUNCTION notify_contact_addition_trigger();
